name: empresas_flutter
description: Teste tecnico - ioasys
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^0.14.2
  fpdart: ^0.0.7
  flutter_bloc: ^7.1.0
  dio: ^4.0.0
  flutter_secure_storage: ^4.2.0
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  string_validator: ^0.3.0
  cached_network_image: ^3.0.0
  flutter_modular: ^3.3.1

dev_dependencies:
  bloc_test: ^8.1.0
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  mocktail: ^0.1.4
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/home_bg.png
    - assets/images/home_min_bg.png
    - assets/images/splash_bg.png
    - assets/images/logo_home.png
    - assets/images/logo_home2.png
    - assets/images/ellipse.svg
    - assets/images/login_bg.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
