name: empresas_flutter
description: Teste tecnico - ioasys
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^0.14.2
  fpdart: ^0.0.7
  flutter_bloc: ^7.0.1
  dio: ^4.0.0
  flutter_secure_storage: ^4.2.0
  flow_builder: ^0.0.3

dev_dependencies:
  bloc_test: ^8.0.2
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  mocktail: ^0.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_bg.png
    - assets/images/logo_home.png

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
